# Deploy to Kubernetes
# Build a Docker image, push to an Azure Container Registry, and deploy it to Azure Kubernetes Service.
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation - Docker Hub/ACR/...
  dockerRegistryServiceConnection: '239fc2dc-8088-4258-9c07-daf517b578e3'
  imageRepository: '$(build.repository.name)'
  containerRegistryName: 'atulmakshelm'

  dockerfilePath: '**/Dockerfile'

  # Kubernetes Environment
  environmentName: 'expressAKS-dev'
  k8sResourceName: "smarthotel-web"
  k8sResourceNamespace: "smarthotel-web"

    # Docker Image Name
  imageName: 'expressaksdemo'
  

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build job
    steps:
    - script: echo hello

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - deployment: Deploy to Kubernetes
    displayName: Deploy job
    environment: expressAKS-dev.smarthotel-web
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Kubernetes@2
            displayName: 'kubectl create imagepullsecret docker-auth'
            inputs:
              containerRegistryType: 'Container Registry'
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
              secretName: 'docker-auth'
              
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              namespace: $(k8sResourceNamespace)
              manifests: |
                manifests/*
              containers: |
                $(containerRegistryName)/$(imageRepository)
