# Deploy to Kubernetes
# Build a Docker image, push to an Azure Container Registry, and deploy it to Azure Kubernetes Service.
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker


variables:

  # Container registry service connection established during pipeline creation - Docker Hub/ACR/...
  dockerRegistryServiceConnection: '6d831aa6-67f2-4ba3-95b1-6f4151b6a1b3'
  imageRepository: '$(build.repository.name)'
  containerRegistryName: 'atulmakshelm'

  dockerfilePath: '**/Dockerfile'

  # Kubernetes Environment
  environmentName: 'expressAKS-dev'
  k8sResourceName: "smarthotel-web"
  k8sResourceNamespace: "smarthotel-web"

    # Docker Image Name
  imageName: 'expressaks-demo'
  

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build job
    steps:
    - script: echo hello
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)


