# Deploy to Kubernetes
# Build a Docker image, push to an Azure Container Registry, and deploy it to Azure Kubernetes Service.
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

  
jobs:
- deployment: DeployToKubernetes
  displayName: DeployK8s
  environment: smarthotel360-dev
  pool: default
  strategy:
    runOnce:
      deploy: 
        steps:
        - script: echo deploy kubernetes

- deployment: DeployWeb
  displayName: Deploy Web
  environment: smarthotel360-dev
  dependsOn: DeployToKubernetes
  pool: default
  strategy:
    runOnce:
      deploy: 
        steps:
        - script: echo deploy web


- deployment: DeployDB
  displayName: Deploy Db
  environment: smarthotel360-dev
  dependsOn: DeployWeb
  pool: default
  strategy:
    runOnce:
      deploy: 
        steps:
        - script: echo deploy web