kind: Deployment
metadata:
  name: {{Image.Repository}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{Image.Repository}}
    spec:
      containers:
      - name: {{Image.Repository}}
        image: {{ContainerRegistry.Name}}/{{Image.Repository}}
        ports:
        - containerPort: {{Container.Port}}
